name: 🧪 Run Tests

on:
  pull_request:
  workflow_call:
  workflow_dispatch:
  push:
    paths:
      - 'src/**/*.nim'
      - 'tests/**/*.nim{s,}'
      - 'nnl.nimble'
      - 'flake.nix'
      - '.github/workflows/test.yml'

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
    - run: echo $LD_LIBRARY_PATH
    - uses: actions/checkout@v4
    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@main
    - uses: DeterminateSystems/magic-nix-cache-action@v2
    - name: run tests
      run: nix develop --command nim c -r tests/tnnl.nim


